allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  sharp: true
  unrs-resolver: true
  vue-demi: true
ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - unrs-resolver
  - vue-demi
minimumReleaseAgeExclude:
  - '@iconify-json/lucide@1.2.117'
  - '@iconify-json/simple-icons@1.2.90'
onlyBuiltDependencies:
  - sharp
