-- ============================================================
-- SQL to run in Supabase Dashboard SQL Editor
-- ============================================================
-- Step 1: Create commander_decks table
-- Step 2: Populate from round_results data
-- ============================================================

-- STEP 1: CREATE TABLE
-- --------------------
CREATE TABLE IF NOT EXISTS public.commander_decks (
    id bigint generated by default as identity not null,
    uuid uuid not null default gen_random_uuid(),
    player_id bigint not null,
    combo_name text null,
    deck_archetype_uuid uuid null,
    commander_1_name text not null,
    commander_2_name text null,
    companion_name text null default ''::text,
    decklist_url text null default ''::text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    CONSTRAINT pk_commander_decks PRIMARY KEY (id),
    CONSTRAINT uq_commander_decks_uuid UNIQUE (uuid),
    CONSTRAINT uq_commander_decks_player_commanders UNIQUE (player_id, commander_1_name, COALESCE(commander_2_name, '')),
    CONSTRAINT fk_commander_decks_player FOREIGN KEY (player_id)
      REFERENCES players(player_id) ON UPDATE CASCADE ON DELETE RESTRICT
) TABLESPACE pg_default;

-- Enable RLS
ALTER TABLE public.commander_decks ENABLE ROW LEVEL SECURITY;

-- Allow authenticated users full access (for development; tighten later)
CREATE POLICY "Allow authenticated all" ON public.commander_decks
    FOR ALL
    TO authenticated
    USING (true)
    WITH CHECK (true);

-- Trigger to auto-update updated_at
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Drop existing trigger if present to avoid errors
DROP TRIGGER IF EXISTS update_commander_decks_updated_at ON public.commander_decks;

CREATE TRIGGER update_commander_decks_updated_at
    BEFORE UPDATE ON public.commander_decks
    FOR EACH ROW
    EXECUTE FUNCTION public.update_updated_at_column();

-- STEP 2: POPULATE FROM round_results
-- ------------------------------------
-- Extract unique (player_id, commander_1, commander_2) combinations
-- Only insert rows where commander_1 is not null and not empty
INSERT INTO public.commander_decks (
    player_id,
    commander_1_name,
    commander_2_name
)
SELECT DISTINCT
    rr.player_id,
    rr.commander_1,
    NULLIF(NULLIF(rr.commander_2, ''), NULL)  -- convert empty string to NULL
FROM public.round_results rr
WHERE rr.commander_1 IS NOT NULL
  AND rr.commander_1 <> ''
ON CONFLICT ON CONSTRAINT uq_commander_decks_player_commanders DO NOTHING;

-- Verify the insert
SELECT COUNT(*) as total_decks FROM public.commander_decks;
